version: '2.0'
services:
  # mongo database
  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    environment:
      - MONGODB_USERNAME=wottactics
      - MONGODB_PASSWORD=wottactics
      - MONGODB_DATABASE=wottactics
    volumes:
       - mongodb-data:/bitnami
  # redis server
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis/data
  # wottactis nodejs app
  nodejs:
    build:
      context: .
    depends_on:
      - mongodb
      - redis
    ports:
      - 8000:80
    links:
      - mongodb
      - redis
    volumes:
      - ./views:/usr/src/app/views
      - ./public:/usr/src/app/public
      - ./helper:/helper

# these volumes are necessary to make the data persitent
volumes:
  mongodb-data:
  redis-data:

# vim:set et ts=8 sts=2 sw=2 ai fenc=utf-8:
